- device_type: cisco_ios
  host: 192.168.177.168
  username: cisco
  password: cisco
  secret: cisco
  timeout: 10
- device_type: cisco_ios
  host: 192.168.177.169
  username: cisco
  password: cisco
  secret: cisco
  timeout: 10
- device_type: cisco_ios
  host: 192.168.177.170
  username: cisco
  password: cisco
  secret: cisco
  timeout: 10
